In [3]:
import numpy as np
from numpy import genfromtxt

In [4]:
data=genfromtxt('DS1_C4_S1_Shopping_Data_Challenge.csv',delimiter=',',skip_header=True)

In [7]:
customer_data = data

In [8]:
data

array([[  1.,  19.,  15.,  39.],
       [  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  5.,  31.,  17.,  40.],
       [  6.,  22.,  17.,  76.],
       [  7.,  35.,  18.,   6.],
       [  8.,  23.,  18.,  94.],
       [  9.,  64.,  19.,   3.],
       [ 10.,  30.,  19.,  72.],
       [ 11.,  67.,  19.,  14.],
       [ 12.,  35.,  19.,  99.],
       [ 13.,  58.,  20.,  15.],
       [ 14.,  24.,  20.,  77.],
       [ 15.,  37.,  20.,  13.],
       [ 16.,  22.,  20.,  79.],
       [ 17.,  35.,  21.,  35.],
       [ 18.,  20.,  21.,  66.],
       [ 19.,  52.,  23.,  29.],
       [ 20.,  35.,  23.,  98.],
       [ 21.,  35.,  24.,  35.],
       [ 22.,  25.,  24.,  73.],
       [ 23.,  46.,  25.,   5.],
       [ 24.,  31.,  25.,  73.],
       [ 25.,  54.,  28.,  14.],
       [ 26.,  29.,  28.,  82.],
       [ 27.,  45.,  28.,  32.],
       [ 28.,  35.,  28.,  61.],
       [ 29.,  40.,  29.,  31.],
       [ 30.,  23.,  29.,  87.],
       [ 3

In [ ]:
# TASK 1

In [10]:
high_spending_customers = customer_data[customer_data[:, 3] > 80]

In [11]:
high_spending_customers

array([[  2.,  21.,  15.,  81.],
       [  8.,  23.,  18.,  94.],
       [ 12.,  35.,  19.,  99.],
       [ 20.,  35.,  23.,  98.],
       [ 26.,  29.,  28.,  82.],
       [ 30.,  23.,  29.,  87.],
       [ 34.,  18.,  33.,  92.],
       [ 36.,  21.,  33.,  81.],
       [ 42.,  24.,  38.,  92.],
       [124.,  39.,  69.,  91.],
       [128.,  40.,  71.,  95.],
       [136.,  29.,  73.,  88.],
       [142.,  32.,  75.,  93.],
       [144.,  32.,  76.,  87.],
       [146.,  28.,  77.,  97.],
       [150.,  34.,  78.,  90.],
       [152.,  39.,  78.,  88.],
       [156.,  27.,  78.,  89.],
       [162.,  29.,  79.,  83.],
       [164.,  31.,  81.,  93.],
       [168.,  33.,  86.,  95.],
       [174.,  36.,  87.,  92.],
       [176.,  30.,  88.,  86.],
       [180.,  35.,  93.,  90.],
       [182.,  32.,  97.,  86.],
       [184.,  29.,  98.,  88.],
       [186.,  30.,  99.,  97.],
       [190.,  36., 103.,  85.],
       [194.,  38., 113.,  91.],
       [200.,  30., 137.,  83.]])

In [12]:
# TASK 2

In [13]:
young_customers = [customer for customer in customer_data if 20 <= customer[1] <= 24]

In [14]:
young_customers

[array([ 2., 21., 15., 81.]),
 array([ 3., 20., 16.,  6.]),
 array([ 4., 23., 16., 77.]),
 array([ 6., 22., 17., 76.]),
 array([ 8., 23., 18., 94.]),
 array([14., 24., 20., 77.]),
 array([16., 22., 20., 79.]),
 array([18., 20., 21., 66.]),
 array([30., 23., 29., 87.]),
 array([32., 21., 30., 73.]),
 array([36., 21., 33., 81.]),
 array([40., 20., 37., 75.]),
 array([42., 24., 38., 92.]),
 array([46., 24., 39., 65.]),
 array([79., 23., 54., 52.]),
 array([85., 21., 54., 57.]),
 array([88., 22., 57., 55.]),
 array([96., 24., 60., 52.]),
 array([100.,  20.,  61.,  49.]),
 array([101.,  23.,  62.,  41.]),
 array([106.,  21.,  62.,  42.]),
 array([125.,  23.,  70.,  29.]),
 array([135.,  20.,  73.,   5.])]

In [15]:
# TASK 3

In [21]:
annual_incomes = customer_data  # Extract the annual incomes from the data

lowest_income = np.min(annual_incomes)  # Find the lowest income
highest_income = np.max(annual_incomes)  # Find the highest income

In [22]:
print(lowest_income)
print(highest_income)

1.0
200.0


In [23]:
# TASK 4

In [43]:

filtered_customers = data[(data[:, 1] < 45) & (data[:, 2] > 35) & (data[:, 3] > 75)]

print(filtered_customers)

num_customers = len(filtered_customers)
print(num_customers)


[[ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [126.  31.  70.  77.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [154.  38.  78.  76.]
 [156.  27.  78.  89.]
 [158.  30.  78.  78.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [196.  35. 120.  79.]
 [200.  30. 137.  83.]]
26


In [44]:
# TASK 5

In [46]:
data = np.random.randint(10, 51, len(data))

print(data)

[40 40 38 33 45 26 41 44 45 33 19 16 29 32 28 34 26 44 33 19 31 15 35 40
 45 22 20 11 49 34 26 21 21 17 22 17 44 45 27 32 15 46 15 38 48 19 17 44
 28 35 28 22 43 40 47 38 25 31 39 40 44 44 47 29 37 43 50 45 50 30 36 39
 33 33 25 17 24 10 14 46 27 14 10 11 45 26 24 22 37 26 33 18 30 41 34 13
 23 28 42 13 38 50 23 47 39 32 50 12 32 38 40 28 21 27 32 22 29 20 38 38
 22 29 13 38 45 27 18 13 21 19 16 45 37 14 47 29 37 29 30 25 36 31 24 10
 15 29 31 44 28 40 24 17 35 35 49 11 45 33 25 50 38 39 48 28 39 14 15 41
 46 28 27 39 31 43 12 50 49 19 19 41 11 45 16 17 44 22 14 26 49 12 39 34
 16 48 30 10 47 27 27 14]
